"""data/*.course.json → relay/size.mjs(코스 정원) · relay/names.mjs(정식 지명). 손으로 옮기지 않는다.
경쟁전은 서버가 정답을 판정하므로 중계기가 지명을 그대로 들고 있어야 한다.

    python3 tools/build_size.py
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
rows = []
for p in sorted((root / 'data').glob('*.course.json')):
    names = [it['name'] for it in json.loads(p.read_text())['items']]
    rows.append((p.name.replace('.course.json', ''), names))

lines = [
    '/* generated by tools/build_size.py — 코스 정원. 손으로 고치지 않는다. */',
    'export const SIZE = {',
]
for i, (slug, names) in enumerate(rows):
    comma = ',' if i < len(rows) - 1 else ''
    lines.append(f"  '{slug}': {len(names)}{comma}")
lines.append('};')
(root / 'relay' / 'size.mjs').write_text('\n'.join(lines) + '\n')

lines = [
    '/* generated by tools/build_size.py — 코스별 정식 지명(코스 순서 그대로). 손으로 고치지 않는다. */',
    'export const NAMES = {',
]
for i, (slug, names) in enumerate(rows):
    comma = ',' if i < len(rows) - 1 else ''
    lines.append(f"  '{slug}': {json.dumps(names, ensure_ascii=False)}{comma}")
lines.append('};')
(root / 'relay' / 'names.mjs').write_text('\n'.join(lines) + '\n')
print(f'{len(rows)} courses → relay/size.mjs · relay/names.mjs')
